### ISSUE TITLE
Chinese translation requested

### ISSUE THREAD

**Issue by Chunbear** [catrenelle/OceanTrip#45]
Hello brother, your project has been very helpful to me. I am a Chinese player and I have a lot of friends around me who are using your plugin.
Have you ever considered adding Chinese support? There are a lot of Chinese players and I can translate it for you.

**Comment by catrenelle** [comment]
I wanted to follow up on this and point to https://github.com/catrenelle/OceanTrip/issues/39 as I know this has been outstanding for a while.

A new enhancement will be pushed shortly that should allow the botbase to work in Non-English mode as well as the CN client. The UI will still have a lot of English elements though until I work out the best way to handle translation.

I'm going to close this ticket and track everything under https://github.com/catrenelle/OceanTrip/issues/39 

Sorry for the delay in responding, and I hope this finds you well.
